languages:
  JavaScript: true
exclude_paths:
- "gulpfile.js"
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
# ... CONFIG CONTENT ...
